# Generated by Django 4.2.1 on 2023-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_picture_date_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m/%d/'),
        ),
    ]
